package main

// Post-anchor diagnostic driver for the frozen W8 implementation.
// It exposes replay of an externally supplied CBTNF-v1 program so the C3
// crossed gate can feed W7-generated bytes into W8. It creates no authority
// and is deliberately compiled without k1_checker_w8.go.

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"
)

type crossReplayOutput struct {
	ProofStatus      string           `json:"proof_status"`
	DirectTraceMap   []map[string]any `json:"direct_trace_map,omitempty"`
	ReplayTraceMap   []map[string]any `json:"replay_trace_map,omitempty"`
	DirectRealize    [][]string       `json:"direct_realize,omitempty"`
	ReplayGas        int              `json:"replay_gas,omitempty"`
	DirectGraphID    string           `json:"direct_graph_id,omitempty"`
	DirectTraceMapID string           `json:"direct_trace_map_id,omitempty"`
	Reason           string           `json:"reason,omitempty"`
}

func traceJSON(ts []TraceEntry) []map[string]any {
	out := make([]map[string]any, 0, len(ts))
	for _, t := range ts {
		p := map[string]string{}
		for k, v := range t.Point {
			p[k] = v
		}
		out = append(out, map[string]any{"point": p, "payloads": append([]string{}, t.Payloads...)})
	}
	return out
}

func relationJSON(rel map[pair]bool) [][]string {
	rows := make([]pair, 0, len(rel))
	for p := range rel {
		rows = append(rows, p)
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].W == rows[j].W {
			return rows[i].C < rows[j].C
		}
		return rows[i].W < rows[j].W
	})
	out := make([][]string, 0, len(rows))
	for _, p := range rows {
		out = append(out, []string{p.W, p.C})
	}
	return out
}

func main() {
	claimP := flag.String("claim", "", "exact W0 claim")
	profileP := flag.String("profile", "", "exact MFST profile")
	programP := flag.String("program", "", "externally supplied C2 program")
	flag.Parse()
	if *claimP == "" || *profileP == "" || *programP == "" {
		b, _ := json.Marshal(crossReplayOutput{ProofStatus: "REJECTED", Reason: "missing required argument"})
		fmt.Println(string(b))
		return
	}
	claimRaw, e1 := os.ReadFile(*claimP)
	profileRaw, e2 := os.ReadFile(*profileP)
	programRaw, e3 := os.ReadFile(*programP)
	if e1 != nil || e2 != nil || e3 != nil {
		e := e1
		if e == nil {
			e = e2
		}
		if e == nil {
			e = e3
		}
		b, _ := json.Marshal(crossReplayOutput{ProofStatus: "REJECTED", Reason: e.Error()})
		fmt.Println(string(b))
		return
	}
	claim, e := parseClaim(claimRaw)
	if e != nil {
		b, _ := json.Marshal(crossReplayOutput{ProofStatus: "REJECTED", Reason: e.Error()})
		fmt.Println(string(b))
		return
	}
	m, e := parseModel(profileRaw, claim)
	if e != nil {
		b, _ := json.Marshal(crossReplayOutput{ProofStatus: "REJECTED", Reason: e.Error()})
		fmt.Println(string(b))
		return
	}
	direct, e := executeMFST(m)
	if e != nil {
		b, _ := json.Marshal(crossReplayOutput{ProofStatus: "REJECTED", Reason: e.Error()})
		fmt.Println(string(b))
		return
	}
	replay, gas, e := replayC2(programRaw, m)
	if e != nil {
		status := "REJECTED"
		if _, ok := e.(unsupportedError); ok {
			status = "UNSUPPORTED"
		}
		b, _ := json.Marshal(crossReplayOutput{ProofStatus: status, Reason: e.Error()})
		fmt.Println(string(b))
		return
	}
	out := crossReplayOutput{
		ProofStatus:      "ACCEPTED",
		DirectTraceMap:   traceJSON(direct.Traces),
		ReplayTraceMap:   traceJSON(replay),
		DirectRealize:    relationJSON(direct.Relation),
		ReplayGas:        gas,
		DirectGraphID:    direct.GraphID,
		DirectTraceMapID: direct.TraceID,
	}
	b, _ := json.Marshal(out)
	fmt.Println(string(b))
}
